export const errorCodes = {
  NAME_REQUIRED: 'NAME_REQUIRED',
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  EMAIL_INVALID: 'EMAIL_INVALID',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  ROLE_REQUIRED: 'ROLE_REQUIRED'
}
